# Forms
forms:
    quick:

        # Form name
        name: Quick Enquiry

        # Send an email?
        email: true

        # Save to a database?
        #
        # @NOTE This option requires you to have 'db'
        # defined in your config with connection details
        db: true

        # Email recipient
        recipient: chris@resknow.co.uk

        # Email subject
        subject: New Message From Your Website

        # The message shown on success
        # @NOTE Only shown if location is not set.
        success_message: Thank you. Your message has been sent.

        # Where to redirect the user on success
        location: /contact/thanks

        # Form fields
        fields:

            # Form name (used in HTML input)
            name:

                # Label
                label: Name

                # HTML type
                type: text

                # Validation rules
                validate: required

                # Filter rules
                filter: trim|sanitize_string

                # For Validation and Filter
                # See wixel/gump

            email:
                label: E-mail address
                type: email
                placeholder: E-mail address
                validate: required|valid_email
                filter: trim

            ########################################
            # Custom Field Types
            #
            # These field types are displayed
            # as custom field types, but their
            # values are submitted in hidden
            # text fields, so you can validate
            # and filter them like other fields
            ########################################

            # Custom Content
            #
            # This field doesn't submit anything
            # but will load a partial from your
            # partials folder.
            custom-message:
                label: Custom Message
                type: content
                partial: content

            # Datepicker Field Type
            delivery:
                label: Delivery Date
                type: datepicker
                validate: required
                filter: trim|sanitize_string

            # Choice Field Type
            service:
                label: Service
                type: choice
                validate: required
                filter: trim|sanitize_string
                options:
                    web-design: Web Design
                    web-development: Web Development
                    logo-design: Logo Design

            phone:
                label: Phone number
                type: tel
                placeholder: Phone number
                validate: required|numeric
                filter: trim|sanitize_numbers
            message:
                label: Message
                type: textarea
                placeholder: Enter your message
                validate: required
                filter: trim|sanitize_string
